version: '3.7'

services:
  web:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default.html:/usr/share/nginx/html/index.html
    depends_on:
      - server
    networks:
      - ts-node-server

  server:
    secrets:
      - APP_PORT
      - APP_PROTOCOL
      - APP_HOST
      - BCRYPT_SALT
      - BCRYPT_MAX_BYTES
      - JWT_SECRET
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_PORT
      - DATABASE_URL
    environment:
      - APP_PORT_FILE=/run/secrets/APP_PORT
      - APP_PROTOCOL_FILE=/run/secrets/APP_PROTOCOL
      - APP_HOST_FILE=/run/secrets/APP_HOST
      - BCRYPT_SALT_FILE=/run/secrets/BCRYPT_SALT
      - BCRYPT_MAX_BYTES_FILE=/run/secrets/BCRYPT_MAX_BYTES
      - JWT_SECRET_FILE=/run/secrets/JWT_SECRET
      - DB_HOST_FILE=/run/secrets/DB_HOST
      - DB_USER_FILE=/run/secrets/DB_USER
      - DB_PASS_FILE=/run/secrets/DB_PASS
      - DB_NAME_FILE=/run/secrets/DB_NAME
      - DB_PORT_FILE=/run/secrets/DB_PORT
      - DATABASE_URL_FILE=/run/secrets/DATABASE_URL
    depends_on:
      - mysqldb
    networks:
      - ts-node-server
  mysqldb:
    image: mysql:8.0.28-oracle
    command: --authentication_policy=mysql_native_password
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/mysql-healthcheck.sh
      interval: 11s
      timeout: 5s
      retries: 5
    secrets:
      - DB_USER
      - DB_PASS
      - DB_NAME
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    networks:
      - ts-node-server

secrets:
  APP_PORT:
    file: ./secrets/APP_PORT
  NODE_ENV:
    file: ./secrets/NODE_ENV
  APP_PROTOCOL:
    file: ./secrets/APP_PROTOCOL
  APP_HOST:
    file: ./secrets/APP_HOST
  BCRYPT_SALT:
    file: ./secrets/BCRYPT_SALT
  BCRYPT_MAX_BYTES:
    file: ./secrets/BCRYPT_MAX_BYTES
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  DB_HOST:
    file: ./secrets/DB_HOST
  DB_USER:
    file: ./secrets/DB_USER
  DB_PASS:
    file: ./secrets/DB_PASS
  DB_NAME:
    file: ./secrets/DB_NAME
  DB_PORT:
    file: ./secrets/DB_PORT
  DATABASE_URL:
    file: ./secrets/DATABASE_URL
