version: '3.7'

services:
  web:
    deploy:
      mode: global
    depends_on:
      - server
    networks:
      - app
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/nginx/default.html:/usr/share/nginx/html/index.html

  server:
    image: 127.0.0.1:5000/ts-app:0.0.1
    command: npm run start
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  mysqldb:
    volumes:
      - mysql_prod:/var/lib/mysql

volumes:
  mysql_prod:
    driver: local

networks:
  app:
    driver: overlay
