version: '3.7'

services:
  web:
    restart: on-failure
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/nginx/default.html:/usr/share/nginx/html/index.html

  server:
    tty: true
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: .
      target: dev
    restart: on-failure
    volumes:
      - /app/node_modules
      - ./:/app
    command: npm run dev

  mysqldb:
    tty: true
    restart: on-failure
    volumes:
      - mysql_dev:/var/lib/mysql
    ports:
      - '$DB_PORT:3306'

volumes:
  mysql_dev:
    driver: local

networks:
  app:
    driver: bridge
