version: '3.7'

services:
  web:
    depends_on:
      server:
        condition: service_healthy

  server:
    tty: true
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: .
      target: dev
    environment:
      - NODE_ENV=development
    ports:
      - '$APP_PORT:4000'
    restart: on-failure
    volumes:
      - ./:/app
      - /app/node_modules
    command: [ "bash", "-c", "./db_deploy.sh && npm run dev" ]

  mysqldb:
    tty: true
    restart: on-failure
    volumes:
      - mysql_dev:/var/lib/mysql
    ports:
      - '$DB_PORT:3306'

volumes:
  mysql_dev:
    driver: local

networks:
  ts-node-server:
    driver: bridge
