version: '3.7'

services:
  server:
    depends_on:
      - mysqldb
    networks:
      - app
    secrets:
      - APP_PORT
      - APP_PROTOCOL
      - APP_HOST
      - BCRYPT_SALT
      - BCRYPT_MAX_BYTES
      - JWT_SECRET
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_PORT
      - DATABASE_URL
    environment:
      - APP_PORT_FILE=/run/secrets/APP_PORT
      - APP_PROTOCOL_FILE=/run/secrets/APP_PROTOCOL
      - APP_HOST_FILE=/run/secrets/APP_HOST
      - BCRYPT_SALT_FILE=/run/secrets/BCRYPT_SALT
      - BCRYPT_MAX_BYTES_FILE=/run/secrets/BCRYPT_MAX_BYTES
      - JWT_SECRET_FILE=/run/secrets/JWT_SECRET
      - DB_HOST_FILE=/run/secrets/DB_HOST
      - DB_USER_FILE=/run/secrets/DB_USER
      - DB_PASS_FILE=/run/secrets/DB_PASS
      - DB_NAME_FILE=/run/secrets/DB_NAME
      - DB_PORT_FILE=/run/secrets/DB_PORT
      - DATABASE_URL_FILE=/run/secrets/DATABASE_URL

  mysqldb:
    networks:
      - app
    image: mysql:8.0.28-oracle
    volumes:
      - ./src/healthchecks:/healthchecks
    command: --authentication_policy=mysql_native_password
    healthcheck:
      test: /healthchecks/mysql-healthcheck.sh
      interval: 11s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    secrets:
      - DB_USER
      - DB_PASS
      - DB_NAME
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/DB_PASS
      - MYSQL_DATABASE_FILE=/run/secrets/DB_NAME
      - MYSQL_USER_FILE=/run/secrets/DB_USER
      - MYSQL_PASSWORD_FILE=/run/secrets/DB_PASS

secrets:
  APP_PORT:
    file: ./src/secrets/APP_PORT
  APP_PROTOCOL:
    file: ./src/secrets/APP_PROTOCOL
  APP_HOST:
    file: ./src/secrets/APP_HOST
  BCRYPT_SALT:
    file: ./src/secrets/BCRYPT_SALT
  BCRYPT_MAX_BYTES:
    file: ./src/secrets/BCRYPT_MAX_BYTES
  JWT_SECRET:
    file: ./src/secrets/JWT_SECRET
  DB_HOST:
    file: ./src/secrets/DB_HOST
  DB_USER:
    file: ./src/secrets/DB_USER
  DB_PASS:
    file: ./src/secrets/DB_PASS
  DB_NAME:
    file: ./src/secrets/DB_NAME
  DB_PORT:
    file: ./src/secrets/DB_PORT
  DATABASE_URL:
    file: ./src/secrets/DATABASE_URL
