version: '3.7'

services:
  mysqldb:
    image: mysql:8.0.28-oracle
    command: --authentication_policy=mysql_native_password
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/mysql-healthcheck.sh
      interval: 11s
      timeout: 5s
      retries: 5
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    networks:
      - ts-node-server

networks:
  ts-node-server:
    driver: bridge
