version: '3.7'

services:
  server:
    tty: true
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: ../
      target: test
    restart: 'no'
    command: npm run exec-tests

  mysqldb:
    tty: true
    build:
      context: ../
      target: mysql
    restart: 'no'
    volumes:
      - mysql_test:/var/lib/mysql

volumes:
  mysql_test:
    driver: local

networks:
  app:
    driver: bridge
